---
title: "R Notebook"
output: html_notebook
---
#Packages, Themes and Functions
```{r}
#load Packages
library(mytools)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)
library(stringr)
library(lubridate)
library(zoo)
library(purrr)
library(gtools)
library(data.table)
library(randomForest)
#library(rJava)
library(plm)
```


```{r}
d <- fread("~/Documents/Podcast S1 Forecast/per day data/ondemand_clean.csv") %>% 
  mutate(month_date = as.Date(paste("01-", month, sep = ""), format = "%d-%b-%Y")) %>%
  filter(story_start_date >= as.Date("2016-03-01"))
d[, grep("date", colnames(d))] <- lapply(d[, grep("date", colnames(d))],
                                        function(x) as.Date(x, format = "%Y-%m-%d"))
show_data <- read.csv("~/Documents/Podcast S1 Forecast/per day data/show_data.csv")
show_data$show <- ifelse(show_data$show == "Radiolab Presents: More Perfect",
                           "More Perfect", as.character(show_data$show))
```

```{r}
#dataframe w/the day of release of the first episode
a <- d %>% group_by(show) %>%
  filter(story_start_date == min(story_start_date),
         show %in% show_data$show) %>% 
  summarise(ep = story[1])
#dataframe w not the first story (feed warmer), start date of that one
d <- d %>% filter(show %in% show_data$show,
                  story %!in% a[a$show != "The New Yorker Comment",]$ep) %>%
  group_by(show, story) %>% 
  mutate(story_start_date1 = min(date))
```

#Eliminate feedwarmers, create real story start date 
```{r}
#dataframe w/the day of release of the first episode
a <- d %>% group_by(show) %>%
  filter(story_start_date == min(story_start_date)) %>% 
  summarise(ep = story[1])
#dataframe w not the first story (feed warmer), start date of that one
d <- d %>% filter(story %!in% a[a$show != "The New Yorker Comment",]$ep) %>%
  group_by(show, story) %>% 
  mutate(story_start_date1 = min(date))

temp <- d %>% group_by(show, story) %>%
  summarise(n_sdates = n_distinct(story_start_date),
            story_start_date = min(story_start_date),
            story_start_date1 = min(story_start_date1),
            timediff = difftime(story_start_date1, story_start_date),
            orig_dls = ifelse(length(which(date == min(story_start_date))) == 0, NA,
                              downloads[which(date == min(story_start_date))]),
            new_dls = downloads[which(date == story_start_date1[1])][1]) %>%
  mutate(story_start_date_real =  if_else(is.na(orig_dls) | n_sdates > 1, story_start_date1,
                                  story_start_date)) %>% 
  filter(timediff != 0 |
         n_sdates > 1)

d <- d %>%
  left_join(temp %>% select(show, story, story_start_date_real)) %>% 
  mutate(story_start_date = as.Date(if_else(!is.na(story_start_date_real),
                                   story_start_date_real,
                                   story_start_date))) %>% 
  select(-story_start_date_real)

d$published_that_day <- ifelse(d$date == d$story_start_date, 1, 0)
rm(a,temp)
```



