---
title: "R Notebook"
output: html_notebook
---

```{r}
d <- read.csv("listeners.csv") %>% filter(!is.na(percent_of_total))
d$day_of_week <- factor(d$day_of_week,
                        levels = unique(d$day_of_week))
d <- d %>% group_by(day_of_week) %>%
  arrange(day_of_week,desc(percent_of_total)) %>% 
  mutate(row_n = row_number())

d_compact <- d %>%
  group_by(day_of_week) %>% 
  mutate(show_name = ifelse(row_n > 4, "Other", as.character(show_name))) %>% 
  group_by(day_of_week, show_name) %>% 
  summarise(percent_of_total = round(sum(percent_of_total), 2))


#all
names_temp <- c((d_compact_all %>% #this one refers to the one being created. Fix the code when more time
                              group_by(show_name) %>%
                              summarise(mean = mean(percent)) %>%
                              arrange(desc(mean)))$show_name)
d_compact_all <- d %>% 
  mutate(show_name = ifelse(show_name %in% d_compact$show_name,
                            as.character(show_name), "Other")) %>% 
  group_by(day_of_week, show_name) %>% 
  summarise(percent = sum(percent_of_total)) %>% 
  mutate(show = factor(show_name, levels = rev(c(names_temp[-9], names_temp[9]))))

```

```{r}
d_od <- read.csv("listeners_ondemand.csv") %>% select(-X)
d_od$day_of_week <- factor(d_od$day_of_week,
                        levels = unique(d_od$day_of_week))
d_od <- d_od %>% group_by(day_of_week) %>%
  arrange(day_of_week,desc(percent_of_total)) %>% 
  mutate(row_n = row_number())

d_od_compact <- d_od %>%
  group_by(day_of_week) %>% 
  mutate(show_name = ifelse(row_n > 6, "Other", as.character(show_name))) %>% 
  group_by(day_of_week, show_name) %>% 
  summarise(percent_of_total = round(sum(percent_of_total), 2))


#all
names_temp_od <- c((d_od_compact_all %>%
                              group_by(show_name) %>%
                              summarise(mean = mean(percent)) %>%
                              arrange(desc(mean)))$show_name)
d_od_compact_all <- d_od %>% 
  mutate(show_name = ifelse(show_name %in% d_od_compact$show_name,
                            as.character(show_name), "Other")) %>% 
  group_by(day_of_week, show_name) %>% 
  summarise(percent = sum(percent_of_total)) %>% 
  mutate(show = factor(show_name, levels = rev(c(names_temp_od[-4], names_temp_od[4]))))

```


```{r}
for(i in unique(d_compact_all$day_of_week)){
 print(i)
 p <- ggplot(d_compact_all %>% filter(day_of_week == i)) +
   labs(title = paste("Average Percentage of Unique Listeners by Show. Livestream.",
                      i, sep = " "),
        x = "") +
  geom_bar(aes(x = show,
               y = percent,
               fill = show),
           stat = "identity",
           position = "stack") +
  scale_y_continuous(limits = c(0,50)) +
  coord_flip() +
  my_theme +
  theme(plot.title = element_text(hjust = 1.4),
        legend.position = "none")
  print(p)
}

```

```{r}

animation::saveGIF({
  for(i in unique(d_compact_all$day_of_week)){
 p <- ggplot(d_compact_all %>% filter(day_of_week == i)) +
   labs(title = i,
        x = "") +
  geom_bar(aes(x = show,
               y = percent,
               fill = show),
           stat = "identity",
           position = "stack") +
  scale_y_continuous(limits = c(0,50)) +
  coord_flip() +
  my_theme +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none")
  print(p)
  }
}, ani.width = 800,
 ani.height = 450,
movie.name = "listeners_livestream.gif")

```

```{r}
animation::saveGIF({
  for(i in unique(d_od_compact_all$day_of_week)){
 p <- ggplot(d_od_compact_all %>% filter(day_of_week == i)) +
   labs(title = i,
        x = "") +
  geom_bar(aes(x = show,
               y = percent,
               fill = show),
           stat = "identity",
           position = "stack") +
  scale_y_continuous(limits = c(0,40)) +
  coord_flip() +
  my_theme +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none")
  print(p)
}
}, ani.width = 800,
 ani.height = 450,
movie.name = "listeners_od.gif")
```

#Episode thing
```{r}
otm_episode <- read.csv("otm_ep_listened.csv") %>% select(-X) %>% 
  mutate(minutes_listened = ifelse(minutes_listened > 25, 25, minutes_listened))
plot_median <- median(otm_episode$minutes_listened)

ggplot(otm_episode) +
  labs(title = "",
       x = "Minutes Listened",
       y = "Listeners") +
  geom_histogram(aes(x = minutes_listened),
                  binwidth = 0.5,
                 fill = "#3A8DE9") +
  geom_vline(xintercept = plot_median,
             linetype = "dashed",
             color = "grey") +
  geom_text(aes(x = plot_median,
                y = 1000,
                label = paste("median:",
                              plot_median, sep = " ")),
            color = "grey",
            size = 4,
            nudge_x = -2.2) +
  scale_x_continuous(breaks = seq(0,25,5)) +
  my_theme

ggsave("otmep.png", dpi = 600, width = 8, height = 5)
```

