---
title: "R Notebook"
output: html_notebook
---

```{r}
d <- fread("~/Documents/Podcast S1 Forecast/per day data/ondemand_clean.csv") %>% 
  mutate(month_date = as.Date(paste("01-", month, sep = ""), format = "%d-%b-%Y")) %>%
  filter(story_start_date >= as.Date("2016-03-01"))
d[, grep("date", colnames(d))] <- lapply(d[, grep("date", colnames(d))],
                                        function(x) as.Date(x, format = "%Y-%m-%d"))
compare_data <- d %>%
  filter(between(date,
                 as.Date("2018-04-09"),
                 as.Date("2018-04-16"))) %>% 
  group_by(show, date) %>% 
  summarise(downloads = sum(downloads))

compare_data2 <- compare_data %>%
  mutate(flag = ifelse(between(date, as.Date("2018-04-11"), as.Date("2018-04-14")),
                       1,0)) %>% 
  group_by(show, flag) %>% 
  mutate(avg_1 = round(mean(downloads), 2)) %>% 
  ungroup() %>%
  group_by(show) %>% 
  mutate(avg_2 = round(avg_1/avg_1[1], 5))


for(i in unique(compare_data2$show)){
  print(ggplot(compare_data2 %>% filter(show == i)) +
    labs(title = i) +
    geom_line(data = compare_data2 %>% filter(show == "2 Dope Queens"),
              aes(x = date,
                  y = avg_2),
              color = "red",
              alpha = 0.5) +
    geom_line(aes(x = date,
                  y = avg_2)) +
    coord_cartesian(ylim = c(min(compare_data2$avg_2),
                             max(compare_data2$avg_2))) +
    my_theme)
}

```


#Missing Data LS
```{r}
d_ls <- read.csv("missingdatals.csv")
d_ls$date <- as.Date(d_ls$date, format = "%m/%d/%y")

ggplot(d_ls,
       aes(x = date,
           y = cume,
           color = station)) +
  geom_line() +
  scale_x_date(breaks = c(unique(d_ls$date))) +
  my_theme +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90))

```

```{r}
d_trial <- read.csv("TRIAL.csv")
d_trial$date <- as.Date(paste(0,d_trial$date, sep = ""), format = "$m/$d/%Y")

```

